// Alert
export const SHOW_INFO = "SHOW_INFO";
export const DISMISS_INFO = "DISMISS_INFO";
export const SHOW_ERROR = "SHOW_ERROR";
export const DISMISS_ERROR = "DISMISS_ERROR";

// Async
export const API_CALL_BEGIN = "API_CALL_BEGIN";
export const API_CALL_ERROR = "API_CALL_ERROR";

// Songs
export const LOAD_SONGS_SUCCESS = "LOAD_SONGS_SUCCESS";
export const LOAD_SONG_SUCCESS = "LOAD_SONG_SUCCESS";

export const CREATE_SONG = "CREATE_SONG";
export const CREATE_SONG_SUCCESS = "CREATE_SONG_SUCCESS";
export const UPDATE_SONG_SUCCESS = "UPDATE_SONG_SUCCESS";
export const DELETE_SONG_SUCCESS = "DELETE_SONG_SUCCESS";

export const DELETE_SONG_CONFIRMED = "DELETE_SONG_CONFIRMED";

// Song filter
export const CHANGE_SONG_VIEW = "CHANGE_SONG_VIEW";

export const CHANGE_SONG_AUTHOR = "CHANGE_SONG_AUTHOR";
export const CHANGE_SONG_POET = "CHANGE_SONG_POET";
export const CHANGE_SONG_ARTIST = "CHANGE_SONG_ARTIST";

export const CHANGE_SONG_SEARCH = "CHANGE_SONG_SEARCH";

export const CHANGE_SONG_SORT_ORDER = "CHANGE_SONG_SORT_ORDER";

export const CHANGE_SONG_PAGE = "CHANGE_SONG_PAGE";
export const CHANGE_SONG_PAGE_SIZE = "CHANGE_SONG_PAGE_SIZE";

export const RESET_SONG_FILTER = "RESET_SONG_FILTER";
