export default {
  songs: [],
  songFilter: {
    view: "random",
    author: null,
    poet: null,
    artist: null,
    sort: "name",
    order: "asc",
    start: 0,
    totalCount: 0,
    pageSize: 25,
  },
  authors: [],
  poets: [],
  artists: [],
  genres: [],
  categories: [],
  keys: [],
  apiStatus: {
    count: 0,
    errorMessage: null,
    isUnauthorized: false,
  },
  alert: {
    infoMessage: null,
    errorMessage: null,
  },
  logLevel: 1,
};
