export default {
  song: null,
  songs: null,
  songFilter: {
    search: "",
    view: "random",
    author: null,
    poet: null,
    artist: null,
    sort: "name",
    order: "asc",
    start: 0,
    totalCount: 0,
    pageSize: 25,
  },
  authors: null,
  poets: null,
  artists: null,
  genres: null,
  keys: null,
  apiStatus: {
    count: 0,
    errorMessage: null,
    isUnauthorized: false,
  },
  alert: {
    infoMessage: null,
    errorMessage: null,
  },
  logLevel: 1,
};
